xmonad-utils.cabal: update for x11/x11-extras merge, ghc-6.8.1
Everything compiles except Heval.hs - "src/Heval.hs:66:20: Not in scope: data constructor `Interactive'", and because of the import statements I have no idea where that is supposed to come from.

darcs-hash:20071110231456-f7719-2c0239196ef9a8fc93203c5536c04a1fa65c3f2d.gz